server:
  #    address: [ip address]
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-ohm.cqlwy82kbfnf.ap-northeast-2.rds.amazonaws.com:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: dudthfalstjr12


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분

    hibernate:
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none


    properties:
      hibernate:
        show-sql:true
        format_sql = true
cloud:
  aws:
    s3:
      bucket: ohm-image
    credentials:
      access-key: AKIA2UIUJNLYDGDHMSWI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


logging.level:
  org.hirbernate.SQL: debug

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR


jwt:
  header: Authorization
  secret: Z2ZkZmdkZmxrZ2pkbGZrZ2pzYXNkamtoYXNrZGphaHNka2fahgvfahvduyasdffjkhsgdfjkhasgfjkphaGRhc2Rhc2Rhc2Rhc2Rhc2ZhZmdzZAo=
  access-token-validity-in-seconds: 86400

